# -*- coding: utf-8 -*-
"""Untitled68.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UUVTk5fPqNFYMMq3mnNBpOW2vbGABVvg
"""

import pandas as pd
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
url="/content/Lab_Exam_binary_classification_dataset.xlsx"
df=pd.read_excel(url)
print(df)

df.describe()

df.info()

print(df.columns)

df.isnull().sum()

df=df.dropna(subset=['Target'])
df.isnull().sum()

print(df.describe())
print(df.info())

df.hist(figsize=(10,8))
plt.show()

df['Target']=df['Target'].map({'Yes':1,'No':0})

sns.heatmap(df.corr(),annot=True,cmap='coolwarm')
plt.show()

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
x=df.drop('Target',axis=1)
y=df['Target']

#train test split
X_train,X_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

model=LogisticRegression()
model.fit(X_train,y_train)
model.fit(X_test,y_test)

y_pred=model.predict(X_test)

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_sc = scaler.fit_transform(X_train)
X_test_sc  = scaler.transform(X_test)

print(f'Training samples : {X_train.shape[0]}')
print(f'Testing  samples : {X_test.shape[0]}')

from sklearn.svm import SVC
# Train SVM classifier
svm_model = SVC(kernel='rbf', C=1.0, gamma='scale', random_state=42)
svm_model.fit(X_train_sc, y_train)

print('SVM Model trained successfully!')
print(f'Number of support vectors per class: {svm_model.n_support_}')

# Use Feature1 (index 0) and Feature2 (index 1) for visualization
feat_idx = [0, 1]
feat_names = [x.columns[i] for i in feat_idx]

X_2d = x.iloc[:, feat_idx] # Use x instead of X and select columns by index
X_train_2d, X_test_2d, y_train_2d, y_test_2d = train_test_split(
    X_2d, y, test_size=0.2, random_state=42, stratify=y
)

scaler_2d = StandardScaler()
X_train_2d_sc = scaler_2d.fit_transform(X_train_2d)
X_test_2d_sc  = scaler_2d.transform(X_test_2d)

# Train on 2 features
svm_2d = SVC(kernel='rbf', C=1.0, gamma='scale', random_state=42)
svm_2d.fit(X_train_2d_sc, y_train_2d)

# Create mesh grid
h = 0.02
x_min, x_max = X_train_2d_sc[:, 0].min() - 1, X_train_2d_sc[:, 0].max() + 1
y_min, y_max = X_train_2d_sc[:, 1].min() - 1, X_train_2d_sc[:, 1].max() + 1
xx, yy = np.meshgrid(np.arange(x_min, x_max, h),
                     np.arange(y_min, y_max, h))

Z = svm_2d.predict(np.c_[xx.ravel(), yy.ravel()])
Z = Z.reshape(xx.shape)

# Plot
plt.figure(figsize=(9, 6))
colors_bg  = ['#fdcba8', '#a8edcc'] # Adjusted for binary classes
colors_dot = ['#d95f02', '#1b8a5a'] # Adjusted for binary classes
markers    = ['o', 's'] # Adjusted for binary classes
target_names_map = {0: 'No', 1: 'Yes'} # Custom target names for binary classification

plt.contourf(xx, yy, Z, alpha=0.35,
             levels=[-0.5, 0.5, 1.5], # Adjusted levels for binary classes 0 and 1
             colors=colors_bg)
plt.contour(xx, yy, Z, colors='gray', linewidths=0.6, linestyles='--')

for cls, color, marker in zip(range(2), colors_dot, markers): # Iterate for 2 classes (0 and 1)
    idx = y_train_2d == cls
    plt.scatter(X_train_2d_sc[idx, 0], X_train_2d_sc[idx, 1],
                c=color, marker=marker, edgecolors='k',
                linewidths=0.5, s=70, label=f'{target_names_map[cls]} (train)')
    idx_t = y_test_2d == cls
    plt.scatter(X_test_2d_sc[idx_t, 0], X_test_2d_sc[idx_t, 1],
                c=color, marker=marker, edgecolors='red',
                linewidths=1.5, s=100, alpha=0.8)

plt.xlabel(f'{feat_names[0]} (scaled)', fontsize=12)
plt.ylabel(f'{feat_names[1]} (scaled)', fontsize=12)
plt.title('SVM Decision Boundary\n(Red borders = test points)', fontsize=14, fontweight='bold')
plt.legend(fontsize=9, loc='upper left')
plt.tight_layout()
plt.savefig('decision_boundary.png', dpi=150)
plt.show()
print('Decision boundary plotted using ' + feat_names[0] + ' vs ' + feat_names[1] + '.')

from sklearn.metrics import accuracy_score
# Predictions
y_pred = svm_model.predict(X_test_sc)

acc = accuracy_score(y_test, y_pred)
print(f'Test Accuracy: {acc * 100:.2f}%')

from sklearn.metrics import classification_report
# Detailed Classification Report
print('=== Classification Report ===')
print(classification_report(y_test, y_pred,
                             target_names=['No', 'Yes']))

from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
# Confusion Matrix
fig, axes = plt.subplots(1, 2, figsize=(13, 5))

# Raw counts
cm = confusion_matrix(y_test, y_pred)
disp = ConfusionMatrixDisplay(confusion_matrix=cm,
                              display_labels=['No', 'Yes'])
disp.plot(cmap='Blues', ax=axes[0], colorbar=False)
axes[0].set_title('Confusion Matrix (Counts)', fontsize=13)

# Normalised
cm_norm = cm.astype('float') / cm.sum(axis=1)[:, np.newaxis]
sns.heatmap(cm_norm, annot=True, fmt='.2f', cmap='YlOrRd',
            xticklabels=['No', 'Yes'],
            yticklabels=['No', 'Yes'], ax=axes[1])
axes[1].set_title('Confusion Matrix (Normalised)', fontsize=13)
axes[1].set_xlabel('Predicted')
axes[1].set_ylabel('Actual')

plt.suptitle('SVM Confusion Matrix', fontsize=15, fontweight='bold')
plt.tight_layout()
plt.savefig('confusion_matrix.png', dpi=150)
plt.show()

from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

print("Accuracy:", accuracy_score(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))

from sklearn.model_selection import cross_val_score
# 5-Fold Cross-Validation
from sklearn.pipeline import Pipeline

pipeline = Pipeline([
    ('scaler', StandardScaler()),
    ('svm', SVC(kernel='rbf', C=1.0, gamma='scale', random_state=42))
])

cv_scores = cross_val_score(pipeline, x, y, cv=5, scoring='accuracy')
print(f'5-Fold CV Scores : {np.round(cv_scores * 100, 2)}')
print(f'Mean CV Accuracy : {cv_scores.mean() * 100:.2f}%')
print(f'Std  CV Accuracy : {cv_scores.std()  * 100:.2f}%')

report = classification_report(y_test, y_pred,
                                target_names=['No', 'Yes'],
                                output_dict=True)

print('=' * 55)
print('         MODEL PERFORMANCE SUMMARY (SVM-RBF)')
print('=' * 55)
print(f"  Dataset          : Current Data (1000 samples, 2 classes)")
print(f"  Model            : Support Vector Machine (RBF)")
print(f"  Train / Test     : {X_train.shape[0]} / {X_test.shape[0]}  (80% / 20%)")
print(f"  Test Accuracy    : {acc * 100:.2f}%")
print(f"  Mean CV Accuracy : {cv_scores.mean() * 100:.2f}% \u00b1 {cv_scores.std() * 100:.2f}%")
print('-' * 55)
print(f"{'Class':<15} {'Precision':>10} {'Recall':>9} {'F1-Score':>10}")
print('-' * 55)
for cls_name in ['No', 'Yes']:
    r = report[cls_name]
    print(f"{cls_name:<15} {r['precision']:>10.2f} {r['recall']:>9.2f} {r['f1-score']:>10.2f}")
print('-' * 55)
ma = report['macro avg']
print(f"{'Macro Avg':<15} {ma['precision']:>10.2f} {ma['recall']:>9.2f} {ma['f1-score']:>10.2f}")
print('=' * 55)

